@startuml
class ListOrganizations {
- List<Organization> places
+ List<Organization> getJob()
}
class Organization {
- Link name
- Date dateStart
- Date dateEnd
- String position
- String info
}
class TextSection {
- String info
+ String getInfo()
}
class Resume {
- String uuid
- String fullName
+ EnumMap<ContactType,String> contacts
+ EnumMap<SectionType,Section> sections
+ String getUuid()
+ String getFullName()
+ String getContact(ContactType)
+ Section getSection(SectionType)
}
class Section {
}
enum SectionType {
+  PERSONAL
+  OBJECTIVE
+  ACHIEVEMENT
+  QUALIFICATIONS
+  EXPERIENCE
+  EDUCATION
- String title
+ String getTitle()
}
class Link {
- String name
- String url
+ String getName()
+ String getUrl()
}
enum ContactType {
+  PHONE
+  SKYPE
+  MAIL
+  LINKEDIN
+  GITHUB
+  STACKOVERFLOW
+  HOMEPAGE
- String title
+ String getTitle()
}
class ListSection {
- List<String> info
+ List<String> getInfo()
}


Section <|-- ListOrganizations
Section <|-- TextSection
Section <|-- ListSection
@enduml